#include "app/generator.h"
#include "math/math_inc.h"


// ..._used arrs decls
GENERATOR_USED_ARR_DECL(adjectives);
GENERATOR_USED_ARR_DECL(nouns);
GENERATOR_USED_ARR_DECL(verbs);
GENERATOR_USED_ARR_DECL(settings);
GENERATOR_USED_ARR_DECL(themes);
GENERATOR_USED_ARR_DECL(perspectives);
GENERATOR_USED_ARR_DECL(genres);
GENERATOR_USED_ARR_DECL(twists);


void generator_reset_word_arrays()
{
  // clear ..._used arrs
  GENERATOR_USED_ARR_CLEAR(adjectives);
  GENERATOR_USED_ARR_CLEAR(nouns);
  GENERATOR_USED_ARR_CLEAR(verbs);
  GENERATOR_USED_ARR_CLEAR(settings);
  GENERATOR_USED_ARR_CLEAR(themes);
  GENERATOR_USED_ARR_CLEAR(perspectives);
  GENERATOR_USED_ARR_CLEAR(genres);
  GENERATOR_USED_ARR_CLEAR(twists);
}

// generator_get...(), ...() and ..._IDX() functions

GENERATOR_GET_TEMPLATE(adjective, adjectives);
GENERATOR_WORD_TEMPLATE(ADJECTIVE, adjective, adjectives, ADJECTIVE_COLOR);
GENERATOR_WORD_IDX_TEMLPLATE(ADJECTIVE, adjectives, ADJECTIVE_COLOR);

GENERATOR_GET_TEMPLATE(noun, nouns);
GENERATOR_WORD_TEMPLATE(NOUN, noun, nouns, NOUN_COLOR);
GENERATOR_WORD_IDX_TEMLPLATE(NOUN, nouns, NOUN_COLOR);

GENERATOR_GET_TEMPLATE(verb, verbs);
GENERATOR_WORD_TEMPLATE(VERB, verb, verbs, VERB_COLOR);
GENERATOR_WORD_IDX_TEMLPLATE(VERB, verbs, VERB_COLOR);

GENERATOR_GET_TEMPLATE(setting, settings);
GENERATOR_WORD_TEMPLATE(SETTING, setting, settings, SETTING_COLOR);
GENERATOR_WORD_IDX_TEMLPLATE(SETTING, settings, SETTING_COLOR);

GENERATOR_GET_TEMPLATE(theme, themes);
GENERATOR_WORD_TEMPLATE(THEME, theme, themes, THEME_COLOR);
GENERATOR_WORD_IDX_TEMLPLATE(THEME, themes, THEME_COLOR);

GENERATOR_GET_TEMPLATE(perspective, perspectives);
GENERATOR_WORD_TEMPLATE(PERSPECTIVE, perspective, perspectives, PERSPECTIVE_COLOR);
GENERATOR_WORD_IDX_TEMLPLATE(PERSPECTIVE, perspectives, PERSPECTIVE_COLOR);

GENERATOR_GET_TEMPLATE(genre, genres);
GENERATOR_WORD_TEMPLATE(GENRE, genre, genres, GENRE_COLOR);
GENERATOR_WORD_IDX_TEMLPLATE(GENRE, genres, GENRE_COLOR);

GENERATOR_GET_TEMPLATE(twist, twists);
GENERATOR_WORD_TEMPLATE(TWIST, twist, twists, TWIST_COLOR);
GENERATOR_WORD_IDX_TEMLPLATE(TWIST, twists, TWIST_COLOR);



